server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: drivinghistory-service
          uri: http://localhost:8082
          predicates:
            - Path=/driving-history/**

        - id:  policy-service
          uri: http://localhost:8083
          predicates:
            - Path=/policies/**

        - id: claim-service
          uri: http://localhost:8084
          predicates:
            - Path=/claims/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
