server:
  port: 8083

spring:
  application:
    name: Policy_Service

  datasource:
    #url: jdbc:mysql://localhost:3305/policy_motor_insurance   # DB in Docker
    url: jdbc:mysql://localhost:3306/policy_motor_insurance   # DB Locally
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# Prometheus application.yml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      resilience4j.circuitbreaker.calls: true

# Kafka


# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      # For the UserService → PolicyService call
      userPolicyBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 5
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED

      # ✅ For the PolicyService → DrivingHistoryService call
      policyByHistory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50            # 50% failure rate will trip the circuit
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED