#prometheus
spring:
  application:
    name:Claim_Service

server:
  port=8084:

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"     # exposes all actuator endpoints including prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


