server:
  port:8084

spring:
   application:
     name: claim-service

eureka:
       client:
         service-url:
           defaultZone: http://localhost:8761/eureka/
         register-with-eureka: true
         fetch-registry: true
       instance:
         prefer-ip-address: true

     # optional: prefer IP address for service instance
