pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        IMAGE_NAME = 'rutwikbalkhande/motor-user-service'
        IMAGE_TAG  = 'latest'
        DOCKER_CREDS = credentials('docker-hub-creds')
    }

    stages {

        stage('Build User Service') {
            steps {
                dir('User') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('User') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                  echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --password-stdin
                  docker push $IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }

        stage('Run Docker Compose') {
            steps {
                sh '''
                  docker compose down || true
                  docker compose pull
                  docker compose up -d
                '''
            }
        }

    }
}
